services:
  app:
    container_name: auth-service
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@db/auth_db
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: auth-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db  
    ports:
      - "3306:3306"
    volumes:
      - auth_db_data:/var/lib/mysql

volumes:
  auth_db_data:
