name: Authentication Services CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Install Python 3.13 manually
    - name: Install Python 3.13
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.13 python3.13-distutils

    # Step 3: Set up Python 3.13
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    # Step 4: Install Poetry
    - name: Install Poetry
      run: |
        python3.13 -m pip install poetry

    # Step 5: Set up virtual environment and install dependencies
    - name: Set up virtual environment and install dependencies
      run: |
        poetry env use python3.13
        poetry install --no-root

    # Step 6: Lint with flake8
    - name: Lint with flake8
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Step 7: Run tests with pytest
    - name: Test with pytest
      run: |
        poetry run pytest