name: Auth Service CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t auth-service .

    # Step 3: Run tests inside the container
    - name: Run tests
      run: |
        docker run --rm auth-service poetry run pytest

    # Step 4: Run linting with flake8 inside the container
    - name: Lint with flake8
      run: |
        docker run --rm auth-service poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        docker run --rm auth-service poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics